db:
  host: "sql6.freemysqlhosting.net"
  database: "sql6455846"
  user: "sql6455846"
  password: "537Sr5rYVa"
  port: "3306"
  
secret:
  key: "secure123!"
  password : "![/nudAAaxWZAYL0C6DLq2UQ==]"

http:
  port: "8081"